/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AgcOatHarvestLossInputs {
    'socket': string;
  }
  interface AgcOatHarvestLossInputsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcOatHarvestLossProgress {
    'socket': string;
  }
  interface AgcOatHarvestLossProgressAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcOatHarvestLossResultsPlaceholder {}
  interface AgcOatHarvestLossResultsPlaceholderAttributes extends StencilHTMLAttributes {}

  interface AgcOatHarvestLossResults {
    'socket': string;
  }
  interface AgcOatHarvestLossResultsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcOatHarvestLoss {
    'mode': "full" | "step";
    'socket': string;
    'tract': string;
    'units': any;
  }
  interface AgcOatHarvestLossAttributes extends StencilHTMLAttributes {
    'mode'?: "full" | "step";
    'onAgcCalculated'?: (event: CustomEvent) => void;
    'onAgcStepChanged'?: (event: CustomEvent) => void;
    'socket'?: string;
    'tract'?: string;
    'units'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AgcOatHarvestLossInputs': Components.AgcOatHarvestLossInputs;
    'AgcOatHarvestLossProgress': Components.AgcOatHarvestLossProgress;
    'AgcOatHarvestLossResultsPlaceholder': Components.AgcOatHarvestLossResultsPlaceholder;
    'AgcOatHarvestLossResults': Components.AgcOatHarvestLossResults;
    'AgcOatHarvestLoss': Components.AgcOatHarvestLoss;
  }

  interface StencilIntrinsicElements {
    'agc-oat-harvest-loss-inputs': Components.AgcOatHarvestLossInputsAttributes;
    'agc-oat-harvest-loss-progress': Components.AgcOatHarvestLossProgressAttributes;
    'agc-oat-harvest-loss-results-placeholder': Components.AgcOatHarvestLossResultsPlaceholderAttributes;
    'agc-oat-harvest-loss-results': Components.AgcOatHarvestLossResultsAttributes;
    'agc-oat-harvest-loss': Components.AgcOatHarvestLossAttributes;
  }


  interface HTMLAgcOatHarvestLossInputsElement extends Components.AgcOatHarvestLossInputs, HTMLStencilElement {}
  var HTMLAgcOatHarvestLossInputsElement: {
    prototype: HTMLAgcOatHarvestLossInputsElement;
    new (): HTMLAgcOatHarvestLossInputsElement;
  };

  interface HTMLAgcOatHarvestLossProgressElement extends Components.AgcOatHarvestLossProgress, HTMLStencilElement {}
  var HTMLAgcOatHarvestLossProgressElement: {
    prototype: HTMLAgcOatHarvestLossProgressElement;
    new (): HTMLAgcOatHarvestLossProgressElement;
  };

  interface HTMLAgcOatHarvestLossResultsPlaceholderElement extends Components.AgcOatHarvestLossResultsPlaceholder, HTMLStencilElement {}
  var HTMLAgcOatHarvestLossResultsPlaceholderElement: {
    prototype: HTMLAgcOatHarvestLossResultsPlaceholderElement;
    new (): HTMLAgcOatHarvestLossResultsPlaceholderElement;
  };

  interface HTMLAgcOatHarvestLossResultsElement extends Components.AgcOatHarvestLossResults, HTMLStencilElement {}
  var HTMLAgcOatHarvestLossResultsElement: {
    prototype: HTMLAgcOatHarvestLossResultsElement;
    new (): HTMLAgcOatHarvestLossResultsElement;
  };

  interface HTMLAgcOatHarvestLossElement extends Components.AgcOatHarvestLoss, HTMLStencilElement {}
  var HTMLAgcOatHarvestLossElement: {
    prototype: HTMLAgcOatHarvestLossElement;
    new (): HTMLAgcOatHarvestLossElement;
  };

  interface HTMLElementTagNameMap {
    'agc-oat-harvest-loss-inputs': HTMLAgcOatHarvestLossInputsElement
    'agc-oat-harvest-loss-progress': HTMLAgcOatHarvestLossProgressElement
    'agc-oat-harvest-loss-results-placeholder': HTMLAgcOatHarvestLossResultsPlaceholderElement
    'agc-oat-harvest-loss-results': HTMLAgcOatHarvestLossResultsElement
    'agc-oat-harvest-loss': HTMLAgcOatHarvestLossElement
  }

  interface ElementTagNameMap {
    'agc-oat-harvest-loss-inputs': HTMLAgcOatHarvestLossInputsElement;
    'agc-oat-harvest-loss-progress': HTMLAgcOatHarvestLossProgressElement;
    'agc-oat-harvest-loss-results-placeholder': HTMLAgcOatHarvestLossResultsPlaceholderElement;
    'agc-oat-harvest-loss-results': HTMLAgcOatHarvestLossResultsElement;
    'agc-oat-harvest-loss': HTMLAgcOatHarvestLossElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
